In [1]:
# %matplotlib inline
%matplotlib qt 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Creating a cleaned dataset
np.random.seed(42)
X1_clean = np.array(range(10,30))
X2_clean = np.array(range(10,30))

#Plotting the points
plt.scatter(X1_clean, X2_clean)
plt.grid()

In [3]:
# Adding noise

X1_noise = np.random.randn(1,20)[0]
X2_noise = np.random.randn(1,20)[0]

X1 = X1_clean + X1_noise
X2 = X2_clean + X2_noise

data  = np.column_stack((X1,X2))

#Plotting the data
plt.scatter(X1,X2)


In [4]:
X1_new = X1-np.array(20)
X2_new = X2-np.array(20)
plt.scatter(X1_new,X2_new)

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
data_compressed = pca.fit_transform(data)
pca.explained_variance_ratio_

array([0.98410549, 0.01589451])

In [7]:
data_compressed.shape

(20, 2)

In [9]:
ndc = np.dot(data_compressed,np.array([[1,0],[0,-1]]))

In [10]:
plt.axis('equal')
plt.scatter(ndc[:,0], ndc[:,1])

In [16]:
plt.scatter(X1,X2, color= "#00FFFF")
plt.grid()

In [22]:
plt.scatter(X1,X2,color = "#00FFFF")
plt.scatter(X1_new,X2_new,color = "#ADD8E6")
plt.grid()

In [11]:
plt.scatter(X1,X2, color="#00FFFF")
plt.scatter(X1_new,X2_new,color = "#ADD8E6")
plt.scatter(ndc[:,0], ndc[:,1], color = "#0000A0")
plt.grid()

In [26]:
pca.components_

array([[ 0.68029065,  0.73294245],
       [ 0.73294245, -0.68029065]])

In [48]:
def draw_vector(v0, v1, ax=None):
    ax = ax or plt.gca()
    arrowprops=dict(arrowstyle='->',
                    linewidth=2,
                    shrinkA=0, shrinkB=0)
    ax.annotate('', v1, v0, arrowprops=arrowprops)

# plot data
plt.scatter(X1, X2, alpha=0.2)
for length, vector in zip(pca.explained_variance_ratio_, pca.components_):
    v = vector * 10 * np.sqrt(length)
    draw_vector(pca.mean_, pca.mean_ + v)
plt.axis('equal');

In [49]:
pca.components_

array([[ 0.68029065,  0.73294245],
       [ 0.73294245, -0.68029065]])